In [6]:
3+5

8

In [1]:
import numpy as np
# ベクトルや行列など、機械学習で必要となる形式のデータを簡単に扱える
np = np.array([[1, 2, 3],[1, 2, 3],[1, 2, 3]])
print(np)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [4]:
import numpy as np
ndarray = np.array([1, 2, 3])
print(ndarray)

[1 2 3]


In [2]:
import numpy as np
ndarray = np.arange(0, 5)
ndarray_copy = ndarray.copy() #オブジェクトが変わる
print("original array's id is {}".format(id(ndarray)))
print("copied array's id is {}".format(id(ndarray_copy)))
 
#changing original array
ndarray[:] = 100
print('original array:\n', ndarray)
print('copied array:\n', ndarray_copy)

original array's id is 140480667420032
copied array's id is 140480255305488
original array:
 [100 100 100 100 100]
copied array:
 [0 1 2 3 4]


In [3]:
def add_world(hello):
    hello += ' world'
    return hello
 
h_str = 'hello'
h_list = ['h', 'e', 'l', 'l', 'o']
output_str = add_world(h_str)
output_list = add_world(h_list)
 
print('output_str: {}'.format(output_str))
print('output_list: {}'.format(output_list))
 
print('h_str: {}'.format(h_str))
print('h_list: {}'.format(h_list))

output_str: hello world
output_list: ['h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']
h_str: hello
h_list: ['h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']


In [5]:
import numpy as np
def change_hundred(array):
 
    array[0] = 100
    return array
 
def change_hundred_copy(array):
    
    #.copy() をしないと直接もとの変数を上書きしてしまう(値渡し)
    array_copy = array.copy() 
    array_copy[0] = 100
    return array_copy
 
array_1 = np.arange(0, 4)
array_2 = np.arange(0, 4)
 
output_array = change_hundred(array_1)
output_array_copy = change_hundred_copy(array_2)
 
print('original array_1:\n', array_1)
print('original array_2:\n', array_2)

original array_1:
 [100   1   2   3]
original array_2:
 [0 1 2 3]


In [ ]:
shape = (2, 3, 5) #タプル　２つの配列、３つ次元数、５つの行
zeros = np.zeros(shape)