In [12]:
import numpy as np

# 縦5、横5
random = np.random.randn(5, 5)
print(random)

#max
print('max is')
print(random.max())

#argmax 最大値のindexを求める
print('argmax is')
print(random.argmax())

print(random.flatten()[11])

# min
print('min is')
print(random.min())

# argmin 最小値のindexを求める
print('argmin is')
print(random.argmin())

# mean 平均値を取得します．全ての要素を足して要素数で割った値
print('mean is')
print(random.mean())

# 中央値を取得 真ん中の値 平均値とは意味
# npから取得するのに注意
# median
print('median is')
print(np.median(random))

# 標準偏差(standard deviation)を取得 標準偏差は、データの分散(ばらつき)を示す指標　𝜎(シグマ)
# 各データの値と平均の差を２乗した合計を，データ数で割った正の平方根
#std
print('standard deviation is')
print(random.std())

# 上記の関数は全てnp.関数名(ndarray)で呼ぶことも可能
print(np.max(random))
print(random.max())


# 各行の統計量を計算
# 特定の行，列での統計量を求めたい場合は引数axisを指定
# axis=0を指定すると各列の統計量 axis=1を指定すると各行の統計量を返す
print('axis=0> {}'.format(random.max(axis=0)))
print('axis=1> {}'.format(random.max(axis=1)))

[[ 1.39089895  1.03009795  1.31628301 -1.57890949 -0.11710082]
 [ 2.17524415 -0.99998819  0.2876507  -0.10047319  0.23581132]
 [-1.46578327  0.92828908  0.47216937 -0.19524794 -0.51994401]
 [ 1.02674169 -0.26116552  0.51504077 -0.15704281 -0.29142403]
 [-1.40055943 -0.47358094  1.16063757 -0.14389652  0.56386226]]
max is
2.175244147056753
argmax is
5
0.9282890762388745
min is
-1.5789094914547945
argmin is
3
mean is
0.13590442499137015
median is
-0.10047318964103961
standard deviation is
0.9287370426210988
2.175244147056753
2.175244147056753
axis=0> [ 2.17524415  1.03009795  1.31628301 -0.10047319  0.56386226]
axis=1> [1.39089895 2.17524415 0.92828908 1.02674169 1.16063757]


In [2]:
import numpy as np
from scipy.stats.mstats import gmean

# x=[1,2,3,4,5,6,7,8,9]
x = np.arange(1, 10)

# xの幾何平均を計算
x_gmean = gmean(x)

print(x_gmean)


# 幾何平均で計算したいケースは、比率の平均　geometric mean
# データ数がｎ個あったら、ｎ個のデータを掛け合わせて、そのｎ乗根をとることで得られる値 
# 四角形を思い浮かべるといい ab = √ab2 (√ab x √ab)

# def geo_mean(iterable):
#     a = np.array(iterable)
#     return a.prod()**(1.0/len(a))

#     output_array = geo_mean(iterable)

# def geo_mean_overflow(iterable):
#     a = np.log(iterable)
#     return np.exp(a.sum()/len(a))

4.147166274396913
