要素の統計量を求める

In [6]:
import numpy as np

# 標準正規分布
normal_dist_mat = np.random.randn(5, 5)
print(normal_dist_mat)

#max
print('max is')
print(normal_dist_mat.max())

#argmax 最大値のindex
print('argmax is')
print(normal_dist_mat.argmax())

#min
print('min is')
print(normal_dist_mat.min())

#argmin 最小値のindex
print('min is')
print(normal_dist_mat.argmin())

#mean　平均値　要素の数足して、その分でわる
print('mean is')
print(normal_dist_mat.mean())

#median　中央値
print('median is')
print(np.median(normal_dist_mat))

#std　標準偏差　各データの値と平均の差を２乗した合計を，データ数で割った正の平方根
print('standard deviation is')
print(normal_dist_mat.std())

[[-1.36639289 -0.83997649  0.78907133  0.88684188 -0.05263116]
 [ 0.68830748  0.14657176 -0.61607313  2.13856491 -0.22816847]
 [-1.21315029  1.44743815 -1.49133836 -0.37786093  0.61093828]
 [ 0.55728706  0.72313085 -1.09585274 -0.97770237 -1.36669496]
 [ 1.62856308 -0.89200717  1.22725071 -0.88265723  1.64032508]]
max is
2.138564909983658
argmax is
8
min is
-1.491338360879626
min is
12
mean is
0.04335137422497641
median is
-0.05263116113247132
standard deviation is
1.0775280526597684
